### ISSUE TITLE
I don't get it :-(

### ISSUE THREAD

**Issue by wmertens** [carlsmith/coffeeshop#11]
CS looks awesome but I can't figure out how to use it... The book etc kind of gloss over how to actually get started :sweat_smile:.

**Comment by carlsmith** [comment]
Have you done any JS programming?

**Comment by wmertens** [comment]
No, seriously, I know CoffeeScript and I often frequent jsfiddle and friends but I can't figure out how to work cosh. I see two panes, I can click on stuff and type in the left pane, and I can edit things in the right pane, but nowhere do I see a way to run coffeescript in the browser like a REPL. I must be missing something very basic.

**Comment by wmertens** [comment]
aha: <kbd>Meta</kbd>+<kbd>Enter</kbd> runs things. Would have been nice to see spelled out in home.md...

**Comment by wmertens** [comment]
Ok, how about changing `config.coffee` to have

```coffeescript
# Welcome!
# This pane allows you to write coffeescript, and you can see the result
# on the left. Try writing 'put "Hello, world!"' and pressing Meta+Enter

print "/docs/home.md"
```

That would have helped me.

Also, I now understand _your_ confusion, I used CS like you used it on the forums, for CoffeeShop, and you understood CoffeeScript :grinning:.

**Comment by carlsmith** [comment]
Sorry, yeah, I get you now. There are some docs, but it isn't the easiest thing to figure out. The keybindings should be more obvious. Thanks for the feedback. I will fix that next time I have some time.

Thanks again.

**Comment by carlsmith** [comment]
@wmertens Sorry if I didn't seem to take your input onboard. I was just really busy lately man.

I'm going to be reading over your suggestions and another users in the next week or two, and will start writing new docs. If you have any other ideas on this, let me know. If it wasn't so difficult to grasp what it does. it'd probably pick up more users.

I actually write docs for a living, so it's kind of embarrassing that my own docs are such an epic fail.

Thanks again dude. Your stuff is appreciated.

**Comment by carlsmith** [comment]
@wmertens and @shamrin - I just rewrote all the docs. Thank you for your input.

**Comment by wmertens** [comment]
The new docs are a lot cleare, thanks! One thing I'm still missing though is an example, something nice to play with.
I'm still trying to understand if CoffeeShop can be used instead of jsfiddfle or codepen to try out code interactively, or is it more an environment to learn coffeescript in?

**Comment by carlsmith** [comment]
@wmertens - I've tried to answer the question properly. It's a good question, and it keeps coming up.

I'd like CoffeeShop to be good for learning coding one day, but right now, it's really just ready for people who know CoffeeScript.

You can use like a normal shell, for trying code out, solving little one file problems, hacking JSON APIs, anything interactive. You can also save useful functions and scripts, and then `run` them. You can call `run` scripts from your `config.coffee` too, so you can ready up your shell however you want it to work.

If you create a cool script or utility, you can `publish` it as a gist, and other people can `clone` it. Once you publish it, the Gallery can load it based on the gistID too.

People might only want to run a shared script in Gallery Mode once, just to check it before they clone it, think XSS. Otherwise, it's gonna be CodePen style use cases, basically sharing examples, but in a shell. Being a shell changes the aesthetics a little bit, but the most important difference is how opinionated it is.

If you click on the `auth` link in the shell, you'll see a Markdown page rendered with some plain HTML input tags in. Everything is styled automatically. The CSS is applied to all Markdown for free, and all markup is Markdown in CoffeeShop, so it's really simple and quick to produce something like that in a script. In CodePen, you'd have to do something about the CSS yourself, but would also be free to do it however you pleased.

If you wanted to show of WebDev techniques, CodePen would be a better place. If you want to write something like shell scripts on HTML5 then CoffeeShop would be better, I think.

Ask me to expand on anything you're interested in. Cheers for the feedback too.
